# Generated by Django 5.1.5 on 2025-01-29 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('typology', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('year', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('studio', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.IntegerField(blank=True, null=True)),
                ('soundtrack', models.IntegerField(blank=True, null=True)),
                ('plot', models.IntegerField(blank=True, null=True)),
                ('animations', models.IntegerField(blank=True, null=True)),
                ('unpredictability', models.IntegerField(blank=True, null=True)),
                ('protagonist', models.IntegerField(blank=True, null=True)),
                ('secondary_characters', models.IntegerField(blank=True, null=True)),
                ('plot_armor', models.IntegerField(blank=True, null=True)),
                ('character_development', models.IntegerField(blank=True, null=True)),
                ('villains', models.IntegerField(blank=True, null=True)),
                ('japanese_awkwardness', models.IntegerField(blank=True, null=True)),
                ('story_flow', models.IntegerField(blank=True, null=True)),
                ('dead_moments', models.IntegerField(blank=True, null=True)),
                ('logical_character_choices', models.IntegerField(blank=True, null=True)),
                ('fights', models.IntegerField(blank=True, null=True)),
                ('character_design', models.IntegerField(blank=True, null=True)),
                ('ending', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
