# Generated by Django 5.1.5 on 2025-01-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='animations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='character_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='character_development',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='dead_moments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='ending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='fights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='intro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='japanese_awkwardness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='logical_character_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='plot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='plot_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='protagonist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='secondary_characters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='soundtrack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='story_flow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='unpredictability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='villains',
            field=models.BooleanField(default=False),
        ),
    ]
